export const PERM = {
	DEGREE: {
		LIST: 'DEGREE_LIST',
		ADD: 'DEGREE_ADD',
		EDIT: 'DEGREE_EDIT',
		DELETE: 'DEGREE_DELETE',
		STATUS: 'DEGREE_STATUS',
		EXCEL: 'DEGREE_DOWNLOAD_EXCEL'
	},
	SPECIALIZATION: {
		LIST: 'SPECIALIZATION_LIST',
		ADD: 'SPECIALIZATION_ADD',
		EDIT: 'SPECIALIZATION_EDIT',
		DELETE: 'SPECIALIZATION_DELETE',
		STATUS: 'SPECIALIZATION_STATUS',
		EXCEL: 'SPECIALIZATION_DOWNLOAD_EXCEL'
	},
	CHARGE_SERVICE_TYPE: {
		LIST: 'CHARGE_SERVICE_TYPE_LIST',
		ADD: 'CHARGE_SERVICE_TYPE_ADD',
		EDIT: 'CHARGE_SERVICE_TYPE_EDIT',
		DELETE: 'CHARGE_SERVICE_TYPE_DELETE',
		STATUS: 'CHARGE_SERVICE_TYPE_STATUS',
		EXCEL: 'CHARGE_SERVICE_TYPE_DOWNLOAD_EXCEL'
	},
	DOCTOR_TYPE: {
		LIST: 'DOCTOR_TYPE_LIST',
		ADD: 'DOCTOR_TYPE_ADD',
		EDIT: 'DOCTOR_TYPE_EDIT',
		DELETE: 'DOCTOR_TYPE_DELETE',
		STATUS: 'DOCTOR_TYPE_STATUS',
		EXCEL: 'DOCTOR_TYPE_DOWNLOAD_EXCEL'
	},
	CONSULTATION_CHARGE: {
		LIST: 'CONSULTATION_CHARGE_LIST',
		ADD: 'CONSULTATION_CHARGE_ADD',
		EDIT: 'CONSULTATION_CHARGE_EDIT',
		DELETE: 'CONSULTATION_CHARGE_DELETE',
		VIEW: 'CONSULTATION_CHARGE_VIEW'
	},
	COMMISSION: {
		LIST: 'COMMISSION_LIST',
		ADD: 'COMMISSION_ADD',
		EDIT: 'COMMISSION_EDIT',
		DELETE: 'COMMISSION_DELETE',
		STATUS: 'COMMISSION_STATUS',
		VIEW: 'COMMISSION_VIEW'
	},
	DOCTOR_DASHBOARD: {
		VIEW: 'DOCTOR_DASHBOARD_VIEW',
		EXCEL: 'DOCTOR_DASHBOARD_DOWNLOAD_EXCEL'
	},
	DOCTOR: {
		LIST: 'DOCTOR_LIST',
		ADD: 'DOCTOR_ADD',
		EDIT: 'DOCTOR_EDIT',
		DELETE: 'DOCTOR_DELETE',
		STATUS: 'DOCTOR_STATUS',
		EXCEL: 'DOCTOR_DOWNLOAD_EXCEL',
		ASSIGN_LOGIN: 'DOCTOR_ASSIGN_LOGIN'
	},
	DOCTOR_ONBOARDING: {
		LIST: 'DOCTOR_ONBOARDING_LIST',
		ADD: 'DOCTOR_ONBOARDING_ADD',
		EDIT: 'DOCTOR_ONBOARDING_EDIT',
		VIEW: 'DOCTOR_ONBOARDING_VIEW',
		DELETE: 'DOCTOR_ONBOARDING_DELETE',
		APPROVE: 'DOCTOR_ONBOARDING_APPROVE',
		REJECT: 'DOCTOR_ONBOARDING_REJECT',
		SEND_BACK: 'DOCTOR_ONBOARDING_SEND_BACK'
	},
	DOCTOR_AUDIT_TRAIL: {
		LIST: 'DOCTOR_AUDIT_TRAIL_LIST',
		VIEW: 'DOCTOR_AUDIT_TRAIL_VIEW'
	},
	DOCTOR_REPORT: {
		REGISTRATION_EXPIRY: 'DOCTOR_REPORT_REGISTRATION_EXPIRY',
		COMMISSION: 'DOCTOR_REPORT_COMMISSION',
		INCOME: 'DOCTOR_REPORT_INCOME'
	}
};
