/**
 * Central permission key registry.
 *
 * Every key used in can() / canAll() must be defined here.
 * Create matching permissions in Permission Category with the EXACT same key string.
 *
 * Structure per module:
 *   LIST   – view the list page (also used as the base for all sub-actions)
 *   ADD    – show Add button / access add form
 *   EDIT   – show Edit button / access edit form
 *   DELETE – show Delete button
 *   STATUS – show Status toggle
 *   EXCEL  – show Download Excel button
 */

// ─── Employees ───────────────────────────────────────────────────────────────
export const PERM = {
	EMPLOYEE: {
		LIST: 'EMPLOYEE_LIST',
		ADD: 'EMPLOYEE_ADD',
		EDIT: 'EMPLOYEE_EDIT',
		DELETE: 'EMPLOYEE_DELETE',
		STATUS: 'EMPLOYEE_STATUS',
		VIEW: 'EMPLOYEE_VIEW',
		FILTER_DELETED: 'EMPLOYEE_FILTER_DELETED',
		EXCEL: 'EMPLOYEE_DOWNLOAD_EXCEL'
	},

	EMPLOYEE_LEAVE: {
		LIST: 'EMPLOYEE_LEAVE_LIST',
		ADD: 'EMPLOYEE_LEAVE_ADD',
		EDIT: 'EMPLOYEE_LEAVE_EDIT',
		DELETE: 'EMPLOYEE_LEAVE_DELETE',
		APPROVE_TEAM: 'LEAVE_APPROVE_TEAM',
		APPROVE_ALL: 'LEAVE_APPROVE_ALL',
		EXCEL: 'EMPLOYEE_LEAVE_DOWNLOAD_EXCEL'
	},

	LEAVE_BALANCE: {
		LIST: 'LEAVE_BALANCE_LIST',
		SET: 'LEAVE_BALANCE_SET',
		STATUS: 'LEAVE_BALANCE_STATUS',
		EXCEL: 'LEAVE_BALANCE_DOWNLOAD_EXCEL'
	},

	DISCOUNT_ALLOWED: {
		LIST: 'DISCOUNT_ALLOWED_LIST',
		ADD: 'DISCOUNT_ALLOWED_ADD',
		EDIT: 'DISCOUNT_ALLOWED_EDIT',
		DELETE: 'DISCOUNT_ALLOWED_DELETE',
		EXCEL: 'DISCOUNT_ALLOWED_DOWNLOAD_EXCEL'
	},

	// ─── Employee Master Data ─────────────────────────────────────────────────
	DEPARTMENT: {
		LIST: 'DEPARTMENT_LIST',
		ADD: 'DEPARTMENT_ADD',
		EDIT: 'DEPARTMENT_EDIT',
		DELETE: 'DEPARTMENT_DELETE',
		STATUS: 'DEPARTMENT_STATUS',
		EXCEL: 'DEPARTMENT_DOWNLOAD_EXCEL'
	},

	DESIGNATION: {
		LIST: 'DESIGNATIONS_LIST',
		ADD: 'DESIGNATIONS_ADD',
		EDIT: 'DESIGNATIONS_EDIT',
		DELETE: 'DESIGNATIONS_DELETE',
		STATUS: 'DESIGNATIONS_STATUS',
		EXCEL: 'DESIGNATIONS_DOWNLOAD_EXCEL'
	},

	SECTION: {
		LIST: 'SECTION_LIST',
		ADD: 'SECTION_ADD',
		EDIT: 'SECTION_EDIT',
		DELETE: 'SECTION_DELETE',
		STATUS: 'SECTION_STATUS',
		EXCEL: 'SECTION_DOWNLOAD_EXCEL'
	},

	EMPLOYEE_TYPE: {
		LIST: 'EMPLOYEE_TYPE_LIST',
		ADD: 'EMPLOYEE_TYPE_ADD',
		EDIT: 'EMPLOYEE_TYPE_EDIT',
		DELETE: 'EMPLOYEE_TYPE_DELETE',
		STATUS: 'EMPLOYEE_TYPE_STATUS',
		EXCEL: 'EMPLOYEE_TYPE_DOWNLOAD_EXCEL'
	},

	EMPLOYEE_CATEGORY: {
		LIST: 'EMPLOYEE_CATEGORY_LIST',
		ADD: 'EMPLOYEE_CATEGORY_ADD',
		EDIT: 'EMPLOYEE_CATEGORY_EDIT',
		DELETE: 'EMPLOYEE_CATEGORY_DELETE',
		STATUS: 'EMPLOYEE_CATEGORY_STATUS',
		EXCEL: 'EMPLOYEE_CATEGORY_DOWNLOAD_EXCEL'
	},

	// ─── Master Data ──────────────────────────────────────────────────────────
	STATE: {
		LIST: 'STATE_LIST',
		ADD: 'STATE_ADD',
		EDIT: 'STATE_EDIT',
		DELETE: 'STATE_DELETE',
		STATUS: 'STATE_STATUS',
		EXCEL: 'STATE_DOWNLOAD_EXCEL'
	},

	CITY: {
		LIST: 'CITY_LIST',
		ADD: 'CITY_ADD',
		EDIT: 'CITY_EDIT',
		DELETE: 'CITY_DELETE',
		STATUS: 'CITY_STATUS',
		EXCEL: 'CITY_DOWNLOAD_EXCEL'
	},

	ZONE: {
		LIST: 'ZONE_LIST',
		ADD: 'ZONE_ADD',
		EDIT: 'ZONE_EDIT',
		DELETE: 'ZONE_DELETE',
		STATUS: 'ZONE_STATUS'
	},

	AREA: {
		LIST: 'AREA_LIST',
		ADD: 'AREA_ADD',
		EDIT: 'AREA_EDIT',
		DELETE: 'AREA_DELETE',
		STATUS: 'AREA_STATUS'
	},

	BRANCH: {
		LIST: 'BRANCH_LIST',
		ADD: 'BRANCH_ADD',
		EDIT: 'BRANCH_EDIT',
		DELETE: 'BRANCH_DELETE',
		STATUS: 'BRANCH_STATUS',
		EXCEL: 'BRANCH_DOWNLOAD_EXCEL'
	},

	LEAVE_TYPE: {
		LIST: 'LEAVE_TYPE_LIST',
		ADD: 'LEAVE_TYPE_ADD',
		EDIT: 'LEAVE_TYPE_EDIT',
		DELETE: 'LEAVE_TYPE_DELETE',
		STATUS: 'LEAVE_TYPE_STATUS',
		EXCEL: 'LEAVE_TYPE_DOWNLOAD_EXCEL'
	},

	SHARE_TYPE: {
		LIST: 'SHARE_TYPE_LIST',
		ADD: 'SHARE_TYPE_ADD',
		EDIT: 'SHARE_TYPE_EDIT',
		DELETE: 'SHARE_TYPE_DELETE',
		STATUS: 'SHARE_TYPE_STATUS',
		EXCEL: 'SHARE_TYPE_DOWNLOAD_EXCEL'
	},

	// ─── Admin ────────────────────────────────────────────────────────────────
	COLLECTION_TYPE: {
		LIST: 'COLLECTION_TYPE_LIST',
		ADD: 'COLLECTION_TYPE_ADD',
		EDIT: 'COLLECTION_TYPE_EDIT',
		DELETE: 'COLLECTION_TYPE_DELETE'
	},

	DISCOUNT_REASON: {
		LIST: 'DISCOUNT_REASON_LIST',
		ADD: 'DISCOUNT_REASON_ADD',
		EDIT: 'DISCOUNT_REASON_EDIT',
		DELETE: 'DISCOUNT_REASON_DELETE'
	},

	DEPARTMENT_TYPE: {
		LIST: 'DEPARTMENT_TYPE_LIST',
		ADD: 'DEPARTMENT_TYPE_ADD',
		EDIT: 'DEPARTMENT_TYPE_EDIT',
		DELETE: 'DEPARTMENT_TYPE_DELETE'
	},

	// ─── Permission Management ────────────────────────────────────────────────
	PERMISSION_CATEGORY: {
		LIST: 'PERMISSION_CATEGORY_LIST',
		ADD: 'PERMISSION_CATEGORY_ADD',
		EDIT: 'PERMISSION_CATEGORY_EDIT',
		DELETE: 'PERMISSION_CATEGORY_DELETE'
	},

	PERMISSION_GROUP: {
		LIST: 'PERMISSION_GROUP_LIST',
		ADD: 'PERMISSION_GROUP_ADD',
		EDIT: 'PERMISSION_GROUP_EDIT',
		DELETE: 'PERMISSION_GROUP_DELETE'
	},

	USER_GROUP: {
		LIST: 'USER_GROUP_LIST',
		ADD: 'USER_GROUP_ADD',
		EDIT: 'USER_GROUP_EDIT',
		DELETE: 'USER_GROUP_DELETE'
	}
};
